### ISSUE TITLE
TypeError: bufferEs6.hasOwnProperty is not a function |  rollup

### ISSUE THREAD

**Issue by dasharup** [calvinmetcalf/buffer-es6#8]
issue also rasied on rollup,  https://github.com/rollup/rollup/issues/3096

```
/home/codxe/Desktop/imp-apps/dashblogs/deploy/bundle.js:5908
  if (!bufferEs6.hasOwnProperty(key)) continue
                 ^

TypeError: bufferEs6.hasOwnProperty is not a function
    at Object.<anonymous> (/home/codxe/Desktop/imp-apps/dashblogs/deploy/bundle.js:5908:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

can you change the way you are creating the Object, so rollup can pass on that

**Comment by dengnan123** [comment]
any update?

**Comment by paulgrenning** [comment]
Also curious as I have the same issue.

**Comment by bernardoadc** [comment]
I had the same error in rollup, solved by using

```
...
 plugins: [
      resolve({
        ...
        preferBuiltins: false
      }),
      ...
```

**Comment by lemoustachiste** [comment]
has anyone figured out how to solve this issue without disabling the `preferBuiltins` property? It does not look like a viable solution for me

**Comment by YoguiSan** [comment]
> has anyone figured out how to solve this issue without disabling the `preferBuiltins` property? It does not look like a viable solution for me

Also curious, for what I'm doing that solution does not help
